export const APP_CONSTANTS = {
  KEY_MODAL_MESSAGE: 'getModalMessage',
  KEY_EXCHANGE_RATE: 'getExchangeRateFormatted',
  KEY_STX_AMOUNT: 'getStxAmountFormatted',
  KEY_CATEGORIES: 'getCategories',
  KEY_CONFIGURATION_LOGIN: 'getConfigurationLogin',
  KEY_CONFIGURATION: 'getConfiguration',
  KEY_SECTION_HEIGHT: 'getSectionHeight',
  KEY_SECTION_WIDTH: 'getSectionWidth',
  KEY_GALLERY_IMAGE_WIDTH: 'getGalleryImageHeight',

  KEY_APP_MAP: 'applicationStore/getAppmap',
  KEY_APP_MAP_COUNTER: 'applicationStore/getAppmapCounter',
  KEY_APP_MAP_TX_ID: 'applicationStore/getAppmapTxId',
  KEY_APP_MAP_PROJECT: 'applicationStore/getAppmapProject',
  KEY_APP_MAP_APPLICATION_BY_COUNTER: 'applicationStore/getApplication',
  KEY_APP_RPAY_REGISTRY: 'applicationStore/getRpayContractData',
  KEY_APP_MAP_CONTRACT_ID: 'applicationStore/getAppmapContractId',
  KEY_APP_MAP_TRADE_INFO: 'applicationStore/getAppmapTradeInfo',
  KEY_APP_MAP_CLARITY_ASSETS: 'applicationStore/getClarityAssets',
  KEY_APP_MAP_CLARITY_ASSET: 'applicationStore/getClarityAsset',

  SET_CURRENT_SEARCH: 'searchStore/setCurrentSearch',
  KEY_CURRENT_SEARCH: 'searchStore/getCurrentSearch',
  KEY_ASSET: 'searchStore/getAsset',
  KEY_SEARCH_RESULTS: 'searchStore/getSearchResults',
  KEY_MY_PROJECT: 'projectStore/getProject',
  KEY_MY_PROJECTS: 'projectStore/getProjects',
  KEY_CONTRACT: 'projectStore/getContract',
  KEY_FAVOURITES: 'projectStore/getFavourites',

  KEY_PROFILE: 'authStore/getMyProfile',
  KEY_EVENT_CODE: 'getEventCode',
  SET_EVENT_CODE: 'setEventCode',
  DISP_SAVE_PROJECT: 'projectStore/saveProject',
  COMMIT_TOGGLE_WALLET_MODE: 'stacksStore/toggleWalletMode',
  KEY_WALLET_MODE: 'stacksStore/getWalletMode',
  KEY_MACS_WALLET: 'stacksStore/getMacsWallet',
  KEY_SKYS_WALLET: 'stacksStore/getSkysWallet',
  KEY_CONTRACT_DATA: 'stacksStore/getContractData',

  KEY_CONTRACT_ASSET_FROM_HASH: 'contractStore/getContractAssetFromHash'
}
