export const APP_CONSTANTS = {
  KEY_RPAY_CONFIGURATION: 'getRpayConfiguration',
  KEY_MODAL_MESSAGE: 'getModalMessage',
  KEY_EXCHANGE_RATE: 'getExchangeRateFormatted',
  KEY_STX_AMOUNT: 'getStxAmountFormatted',
  KEY_CATEGORIES: 'getCategories',
  KEY_CONFIGURATION_LOGIN: 'getConfigurationLogin',
  KEY_CONFIGURATION: 'getConfiguration',
  KEY_SECTION_HEIGHT: 'getSectionHeight',
  KEY_SECTION_WIDTH: 'getSectionWidth',
  KEY_GALLERY_IMAGE_WIDTH: 'getGalleryImageHeight',

  SET_CURRENT_SEARCH: 'searchStore/setCurrentSearch',
  KEY_CURRENT_SEARCH: 'searchStore/getCurrentSearch',
  KEY_ASSET: 'searchStore/getAsset',
  KEY_SEARCH_RESULTS: 'searchStore/getSearchResults',
  KEY_MY_PROJECT: 'projectStore/getProject',
  KEY_MY_PROJECTS: 'projectStore/getProjects',
  KEY_CONTRACT: 'projectStore/getContract',
  KEY_FAVOURITES: 'projectStore/getFavourites',

  KEY_PROFILE: 'authStore/getMyProfile',
  KEY_EVENT_CODE: 'getEventCode',
  SET_EVENT_CODE: 'setEventCode',
  DISP_SAVE_PROJECT: 'projectStore/saveProject',
  COMMIT_TOGGLE_WALLET_MODE: 'stacksStore/toggleWalletMode',
  KEY_WALLET_MODE: 'stacksStore/getWalletMode',
  KEY_MACS_WALLET: 'stacksStore/getMacsWallet',
  KEY_SKYS_WALLET: 'stacksStore/getSkysWallet',
  KEY_CONTRACT_DATA: 'stacksStore/getContractData',

  KEY_REGISTRY: 'rpayStacksContractStore/getRegistry',
  KEY_REGISTRY_CONTRACT_ID: 'rpayStacksContractStore/getRegistryContractId',
  KEY_TRADE_INFO_FROM_HASH: 'rpayStacksContractStore/getTradeInfoFromHash',
  KEY_APPLICATION_FROM_REGISTRY_BY_CONTRACT_ID: 'rpayStacksContractStore/getApplicationFromRegistryByContractId',
  KEY_ASSET_FROM_CONTRACT_BY_HASH: 'rpayStacksContractStore/getAssetFromContractByHash'
}
